// as parsers matched against specific contexts
// parser-keys should follow special schema:
// parser-<context name>
// same thing for renderers:
// renderer-<context-name>

module.exports = {
  TITLE: 'Works For Me',
  DESCRIPTION: 'Collection of software setups from people who care about tools they use.',
  BASE_URL: 'https://works-for-me.github.io',
  DIST_FOLDER: 'dist',
  // parser keys
  BODY_PARSER_KEY: 'parser-body',
  BIO_PARSER_KEY: 'parser-bio',
  SETUP_PARSER_KEY: 'parser-setup',
  ENVIRONMENT_PARSER_KEY: 'parser-environment',
  ENVIRONMENT_HEADER_PARSER_KEY: 'parser-environment-header',
  TOOLS_LIST_PARSER_KEY: 'parser-tools-list',
  TOOL_ITEM_PARSER_KEY: 'parser-tool-item',
  TOOL_HEAD_PARSER_KEY: 'parser-tool-head',
  TOOL_NAMES_LIST_PARSER_KEY: 'parser-tool-names-list',
  TOOL_NAME_PARSER_KEY: 'parser-tool-name',
  DESCRIPTION_PARSER_KEY: 'parser-description',
  DESCRIPTION_PARAGRAPH_PARSER_KEY: 'parser-description-paragraph',
  DESCRIPTION_LINK_PARSER_KEY: 'parser-description-link',
  IMAGE_PARSER_KEY: 'parser-image',
  // renderer keys
  ROOT_RENDERER_KEY: 'renderer-root',
  HEAD_RENDERER_KEY: 'renderer-head',
  BODY_RENDERER_KEY: 'renderer-body',
  BIO_RENDERER_KEY: 'renderer-bio',
  BIO_LINE_RENDERER_KEY: 'renderer-bio-line',
  SETUP_RENDERER_KEY: 'renderer-setup',
  ENVIRONMENT_RENDERER_KEY: 'renderer-environment',
  DESCRIPTION_RENDERER_KEY: 'renderer-description',
  ENVIRONMENT_HEADER_RENDERER_KEY: 'renderer-environment-header',
  ENVIRONMENT_TITLE_RENDERER_KEY: 'renderer-environment-title',
  TOOLS_LIST_RENDERER_KEY: 'renderer-tools-list',
  TOOL_ITEM_RENDERER_KEY: 'renderer-tool-item',
  TOOL_HEAD_RENDERER_KEY: 'renderer-tool-head',
  TOOL_NAMES_LIST_RENDERER_KEY: 'renderer-tool-names-list',
  TOOL_NAME_RENDERER_KEY: 'renderer-tool-name',
  TOOL_TITLE_RENDERER_KEY: 'renderer-tool-title',
  TOOL_LINK_RENDERER_KEY: 'renderer-tool-link',
  SETUPS_LIST_ITEM_RENDERER_KEY: 'renderer-setups-list-item',
  SETUPS_LIST_RENDERER_KEY: 'renderer-setups-list',
  SETUPS_LIST_ROOT_RENDERER_KEY: 'renderer-setups-list-root',
  SETUP_LATEST_UPDATE_RENDERER_KEY: 'renderer-setup-latest-update',
  RSS_ITEM_TITLE_RENDERER_KEY: 'renderer-rss-item-title',
  RSS_ITEM_DESCRIPTION_RENDERER_KEY: 'renderer-rss-item-description',
  RSS_ITEM_RENDERER_KEY: 'renderer-rss-item',
  RSS_RENDERER_KEY: 'renderer-rss',
  RSS_ITEM_LINK_RENDERER_KEY: 'renderer-rss-item-link',
  RSS_ITEM_AUTHOR_RENDERER_KEY: 'renderer-rss-item-author',
  RSS_ITEM_PUB_DATE_RENDERER_KEY: 'renderer-rss-item-pub-date',
  RSS_ITEM_ID_RENDERER_KEY: 'renderer-rss-item-id',
  DESCRIPTION_PARAGRAPH_RENDERER_KEY: 'renderer-description-paragraph',
  DESCRIPTION_TEXT_RENDERER_KEY: 'renderer-description-text',
  DESCRIPTION_LINK_TITLE_RENDERER_KEY: 'renderer-description-link-title',
  DESCRIPTION_LINK_URL_RENDERER_KEY: 'renderer-description-link-url',
  DESCRIPTION_LINK_RENDERER_KEY: 'renderer-description-link',
  // context names
  ROOT_CONTEXT: 'root',
  HEAD_CONTEXT: 'head',
  HEAD_TITLE_CONTEXT: 'head-title',
  HEAD_DESCRIPTION_CONTEXT: 'head-description',
  BODY_CONTEXT: 'body',
  BIO_CONTEXT: 'bio',
  SETUP_CONTEXT: 'setup',
  ENVIRONMENT_CONTEXT: 'environment',
  ENVIRONMENT_HEADER_CONTEXT: 'environment-header',
  BIO_LINE_CONTEXT: 'bio-line',
  ENVIRONMENT_TITLE_CONTEXT: 'environment-title',
  DESCRIPTION_CONTEXT: 'description',
  TOOLS_LIST_CONTEXT: 'tools-list',
  TOOL_ITEM_CONTEXT: 'tool-item',
  TOOL_HEAD_CONTEXT: 'tool-head',
  TOOL_NAMES_LIST_CONTEXT: 'tool-names-list',
  TOOL_NAME_CONTEXT: 'tool-name',
  TOOL_TITLE_CONTEXT: 'tool-title',
  TOOL_LINK_CONTEXT: 'tool-link',
  SETUPS_LIST_ROOT_CONTEXT: 'setups-list-root',
  SETUPS_LIST_CONTEXT: 'setups-list',
  SETUPS_LIST_ITEM_CONTEXT: 'setups-list-item',
  SETUPS_LIST_ITEM_KEY_CONTEXT: 'setups-list-item-key',
  SETUP_UPDATE_DATE_CONTEXT: 'setup-update-date',
  SETUP_CREATE_DATE_CONTEXT: 'setup-create-date',
  SETUP_LATEST_UPDATE_CONTEXT: 'setup-latest-update',
  SETUP_UPDATE_MESSAGE_CONTEXT: 'setup-update-message',
  COMMIT_MESSAGE_CONTEXT: 'commit-message-context',
  COMMIT_DATE_CONTEXT: 'commit-date-context',
  COMMIT_HASH_CONTEXT: 'commit-hash-context',
  SETUP_URL_CONTEXT: 'setup-url-context',
  RSS_CONTEXT: 'rss',
  RSS_ITEM_CONTEXT: 'rss-item',
  RSS_ITEM_TITLE_CONTEXT: 'rss-item-title',
  RSS_NEW_SETUP_TITLE_CONTEXT: 'rss-new-setup-title',
  RSS_UPDATE_SETUP_TITLE_CONTEXT: 'rss-update-setup-title',
  RSS_ITEM_DESCRIPTION_CONTEXT: 'rss-item-description',
  RSS_ITEM_AUTHOR_CONTEXT: 'rss-item-author',
  RSS_ITEM_PUB_DATE_CONTEXT: 'rss-item-pub-date',
  RSS_ITEM_ID_CONTEXT: 'rss-item-id',
  RSS_ITEM_LINK_CONTEXT: 'rss-item-link',
  DESCRIPTION_PARAGRAPH_CONTEXT: 'description-paragraph',
  DESCRIPTION_TEXT_CONTEXT: 'description-text',
  DESCRIPTION_LINK_CONTEXT: 'description-link',
  DESCRIPTION_LINK_TITLE_CONTEXT: 'description-link-title',
  DESCRIPTION_LINK_URL_CONTEXT: 'description-link-url',
  IMAGE_CONTEXT: 'image',
  IMAGE_TITLE_CONTEXT: 'image-title',
  IMAGE_URL_CONTEXT: 'image-url',
  // lexeme types
  ENV_BULLET_LEXEME: 'env-bullet',
  TOOL_BULLET_LEXEME: 'tool-bullet',
  NEWLINE_LEXEME: 'newline',
  WORD_LEXEME: 'word',
  COMMENT_BULLET_LEXEME: 'comment-bullet',
  IMAGE_BULLET_LEXEME: 'image-bullet',
  // special tokens
  TOOL_BULLET_TOKEN: '>',
  ENV_BULLET_TOKEN: '--',
  COMMENT_BULLET_TOKEN: '//',
  IMAGE_BULLET_TOKEN: '#',
  NEWLINE_TOKEN: '\n',
  RETURN_NEWLINE_TOKEN: '\r\n',
  SPACE_TOKEN: ' ',
  TAB_TOKEN: '\t',
  TOOL_NAMES_SEPARATOR_TOKEN: ',',
  UPDATE_TAG_TOKEN: 'update:',
  NEW_SETUP_TAG_TOKEN: 'new:',
  FIX_TAG_TOKEN: 'fix:',
  BIO_LINE_TYPE_NAME_TOKEN: 'name:',
  BIO_LINE_TYPE_OCCUPATION_TOKEN: 'occupation:',
  BIO_LINE_TYPE_LOCATION_TOKEN: 'location:',
  BIO_LINE_TYPE_LINK_TOKEN: 'link:'
};
