module.exports = [
  { type: 'newline', content: '\n' },
  { type: 'word', content: 'name:' },
  { type: 'word', content: 'John' },
  { type: 'word', content: 'Doe' },
  { type: 'newline', content: '\n' },
  { type: 'newline', content: '\n' },
  { type: 'env-bullet', content: '--' },
  { type: 'word', content: 'desktop' },
  { type: 'newline', content: '\n' },
  { type: 'comment-bullet', content: '//' },
  { type: 'word', content: 'comment' },
  { type: 'word', content: 'one' },
  { type: 'newline', content: '\n' },
  { type: 'tool-bullet', content: '>' },
  { type: 'word', content: 'purpose:' },
  { type: 'word', content: 'tool' },
  { type: 'newline', content: '\n' },
  { type: 'word', content: 'some' },
  { type: 'word', content: 'description' },
  { type: 'newline', content: '\n' },
  { type: 'comment-bullet', content: '//' },
  { type: 'word', content: 'comment' },
  { type: 'word', content: 'two' }
];
